//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polz
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Famil { get; set; }
        public string Telephone { get; set; }
        public string Login { get; set; }
        public int Password { get; set; }
        public int idRol { get; set; }
    
        public virtual Rolei Rolei { get; set; }
    }
}
